window.CHCATECH = {
  config: {
    techDirectorEmail: "chcatech07@gmail.com",
    clubEmail: "chcaracingbaord@gmail.com",
    appsScriptUrl: "https://script.google.com/macros/s/AKfycbwZ4fwBSRaWP9qZTAq81CB4QU1sVPvDrInvrFtpTCH-6NO95XvLIbDFLoM5kin0GBiKQw/exec",
  },
  classes: [
    {
      id: "sportsman",
      label: "Sportsman",
      title: "CHCA 2026 Sportsman Race-Weekend Tech Inspection",
      summary: "Sportsman only. Tight checklist: inspectable items only, with no duplicate checks.",
      extraFields: [],
      sections: [
        {
          title: "Driver Safety Equipment",
          items: [
            "Helmet meets rule: Snell SA2015+ or FIA 8859-2015+, under 10 years old",
            "Full-face helmet present if no full windshield",
            "Head and neck restraint present: SFI 38.1, within 5-year recert window",
            "Harness is 5-point minimum and current",
            "Suit present: SFI 3-2A or FIA 8856-2000 minimum",
            "Gloves present",
            "Shoes / boots present",
          ],
        },
        {
          title: "General Vehicle Safety",
          items: [
            "10 lb pit fire extinguisher present and accessible",
            "On-board fire extinguisher(s) total at least 5 lb and within reach",
            "Seat secure, with headrest and lateral support",
            "Master switch within reach and cuts accessories",
            "Battery secure; covered to prevent spillage; positive terminal covered if gel cell",
            "Throttle has 2 return springs and closes freely",
            "Suspension / steering fasteners use locknut, keying, safety wire, or equivalent",
            "Driveshaft retainer present: 360 degree and mounted forward of centerline",
            "Glass / Lexan rule met",
            "Vehicle numbers visible and readable with required Sportsman suffix",
            "Vehicle clean / neat / race-ready appearance",
          ],
        },
        {
          title: "Sportsman Eligibility and Measurements",
          items: [
            "American manufactured passenger car, 1955 or newer",
            "Hardtop 2-door or 4-door sedan only; not roadster / jeep / taxi / wagon / truck / 4WD",
            "Wheelbase within 1 in of OEM and minimum 105 in",
            "Minimum weight = 9 lb per cubic inch and at least 3000 lb",
            "50% minimum weight on front wheels with driver seated",
            "Actual race weight with driver / fuel / fluids recorded",
            "V8 engine only",
            "Cast iron block only",
            "Cast iron heads only",
            "Stock type distributor only; no magneto",
            "No dry sump; OEM style oil pump only",
            "Engine setback within Sportsman limit",
            "No grinding / smoothing of exterior block or heads; casting numbers intact",
          ],
        },
        {
          title: "Sportsman Construction and Systems",
          items: [
            "Stock appearing body from front to rear; no one-piece front end",
            "Complete body, hood, fenders, bumpers, and grills present",
            "Hood closed with positive fasteners LF and RF; scoop 5 in max",
            "Ballast inside body shell, secure, and numbered",
            "Stock floor pan or minimum 18 ga steel floor with holes filled",
            "Doors fastened with at least two 3/8 in bolts or equivalent per door",
            "Firewall installed, all holes covered, minimum 20 gauge",
            "OEM frame configuration retained within rule limits",
            "Stock type rear end only; no quick-change",
            "Steel driveshaft only",
            "Transmission is OEM and in stock location",
            "Stock OEM suspension / chassis retained; no traction bars; no weight jacks / wedge bolts",
            "Suspension mounted in stock location +/- 1 in",
            "Stock type sway bars only",
            "Tubular upper control arms legal type / stock location / non-adjustable",
            "Tubular lower control arms legal type / stock location",
            "Steering quickener only; OEM box / rack in OEM location",
            "Steering shaft has mid u-joint or collapsible shaft",
            "Shocks in stock location; one per wheel; no heim ends / interchangeable ends",
            "Brake assemblies OEM type; no racing lightweight calipers / rotors / spindles / hubs",
            "Rear disc brakes, if used, fit Sportsman rule",
            "Wheel count is 4; rim width is 10 in max; legal diameter; no bead locks / wide five",
            "DOT-approved tires only; max tread width 11.5 in",
            "Outside edge of tread at top within 1 in of fender / flare",
            "Fuel cell mandatory with check-valve vent and metal skid plate",
            "Single Holley 4412 two-barrel carb only; no mods except choke plate removal",
            "Carb passes go / no-go gauge",
            "No fuel injection",
            "Radiator mounted in front of engine",
            "Self-starter works; vehicle starts under own power",
            "Exhaust exits past driver / seat and is not exposed in driver compartment",
            "Full windshield required and rear window required",
            "Headlight / taillight openings covered if glass removed",
          ],
        },
        {
          title: "Sportsman Roll Cage and Net",
          items: [
            "Steel 4-post roll cage",
            "Roll cage tubing size / wall thickness meets rule",
            "Three horizontal side bars on driver side; two on passenger side",
            "Top roof bar front to back present",
            "Fore-aft braces present per rule",
            "All roll cage members contained within driver compartment",
            "Gussets at four top corners and four post-to-frame mounts",
            "Padding installed from bottom left side to center top of cage",
            "Driver-side wing window support bar welded to cage",
            "Front frame bars present and connected per rule",
            "Helmet clearance to top of cage is 2 in minimum",
            "Driver-side window net installed and mounted per rule",
          ],
        },
      ],
    },
    {
      id: "stock-car",
      label: "Stock Car",
      title: "CHCA 2026 Stock Car Race-Weekend Tech Inspection",
      summary: "Stock Car only. Tight checklist: inspectable items only, with no duplicate checks.",
      extraFields: [],
      sections: [
        {
          title: "Driver Safety Equipment",
          items: [
            "Helmet meets rule: Snell SA2015+ or FIA 8859-2015+, under 10 years old",
            "Full-face helmet present if no full windshield",
            "Head and neck restraint present: SFI 38.1, within 5-year recert window",
            "Harness is 5-point minimum and current",
            "Suit present: SFI 3-2A or FIA 8856-2000 minimum",
            "Gloves present",
            "Shoes / boots present",
          ],
        },
        {
          title: "General Vehicle Safety",
          items: [
            "10 lb pit fire extinguisher present and accessible",
            "On-board fire extinguisher(s) total at least 5 lb and within reach",
            "Seat secure, with headrest and lateral support",
            "Steering wheel quick release present",
            "Master ignition / cutoff within reach, red circle, ON / OFF labeled",
            "Battery secure; if liquid lead-acid, enclosed; positive terminal insulated",
            "Throttle has 2 return springs and closes freely",
            "Suspension / steering fasteners use locknut, keying, safety wire, or equivalent",
            "Driveshaft retainer present: 360 degree and mounted forward of centerline",
            "Scatter shield present if manual clutch",
            "Glass / Lexan rule met",
            "Vehicle numbers visible, contrasting, minimum 13 in on both sides and roof / trunk",
          ],
        },
        {
          title: "Stock Car Eligibility and Measurements",
          items: [
            "American manufactured passenger car",
            "Hardtop 2-door or 4-door sedan only",
            "Engine corporate family matches car manufacturer",
            "Wheelbase within 1 in of body represented and at least 99 in",
            "Frame / suspension type identified",
            "Engine displacement recorded",
            "Minimum weight marked on car and visible at scales",
            "Actual race weight with driver / fuel / fluids recorded",
            "If transverse engine: moved no more than 1.5 in in any direction",
            "If RWD V6 / V8: setback within limit from farthest forward spark plug to spindle centerline, wheels straight, plus 2 in allowance",
            "Meets Stock Car weight chart per CI and 2200 lb minimum",
          ],
        },
        {
          title: "Stock Car Construction and Systems",
          items: [
            "Body remains stock appearing",
            "Complete body, hood, fenders, bumpers, and grills present",
            "Hood closed with positive fasteners LF and RF",
            "Scoop 5 in max and covers air inlet",
            "Fenders modified only for tire clearance and not above stock fender line",
            "Floorboard / underpan present under driver",
            "Firewall present between driver compartment and engine / trunk",
            "Seats are metal or approved composite",
            "Ballast, if used, is inside body shell and secure",
            "No wings, non-stock spoilers, ground effects, flat bottom, or belly pan",
            "No electrical / hydraulic weight shifting device",
            "No driver-operated 4-wheel steering",
            "No electronic traction control",
            "One shock absorber per wheel",
            "Wheel count is 4 and rim width is 12 in max",
            "Tires legal and max tread width is 12.5 in",
            "Fuel cell mandatory, 22 gal max, vented, with skid plate",
            "Electric fuel pump tied to master switch, if used",
            "Normally aspirated only: carburetion or fuel injection",
            "No electronic data acquisition except tachometer and O2 playback",
            "Exhaust exits past driver / front of seat and is not exposed in driver compartment",
            "Full windshield in good condition and rear window present",
            "Headlight / taillight glass removed or replaced with compliant material",
          ],
        },
        {
          title: "Stock Car Roll Cage",
          items: [
            "Steel 4-post roll cage with rear bracing struts",
            "Roll cage tubing size / wall thickness meets rule",
            "Main hoop full width of driver compartment",
            "Three horizontal side bars on driver side",
            "Two side bars on passenger side",
            "Top roof bar front to back present",
            "Gussets at four top corners and four post-to-frame mounts",
            "Padding installed where helmet / contact risk exists",
            "Right-side clearance checked",
            "Helmet clearance to top of roll bar is 2 in minimum",
          ],
        },
      ],
    },
    {
      id: "open-wheel",
      label: "Open Wheel",
      title: "CHCA 2026 Open Wheel Technical Inspection",
      summary: "Open Wheel checklist based on Rulebook Section 300 and General Rule 13.10.",
      extraFields: [],
      sections: [
        {
          title: "Roll Cage and Occupant Protection",
          items: [
            "4-post roll cage installed",
            "Front hoop / crossbar extends above helmet and at least 6 in forward of helmet",
            "Rear hoop extends at least 4 in above helmet without wings, or 2 in with wings above cage",
            "If helmet breaks the roll cage plane, safety nets are installed",
            "Arm restraints installed",
            "Roll bar tubing size / wall thickness meets Open Wheel rule and Section 13.10",
            "Roll cage mounting method meets class rule",
            "Four top cage corners properly gusseted",
            "Padded headrest installed",
          ],
        },
        {
          title: "Vehicle Safety Systems",
          items: [
            "No studded tires",
            "Fuel cell installed",
            "Throttle design passes inspection and returns safely",
            "Fuel shutoff valve is within reach of the strapped-in driver",
            "On-board fire extinguisher system is at least 5 lb",
            "Steering has free movement and turning stops",
            "Pitman arms eliminate reverse steering",
            "Racing type steering wheel installed",
            "Open driveshafts / chains are guarded with approved containment",
            "Approved safety hubs installed",
            "Braking system operates on all 4 wheels with dual master cylinders",
            "Fuel lines and linkage are sufficiently supported or reinforced",
            "Mounted starter system operates with on-board or auxiliary battery power",
          ],
        },
        {
          title: "Body and Chassis",
          items: [
            "Body provides as much coverage as practical",
            "Vehicle is open wheel style with no fenders over all 4 tires",
            "Competition numbers are at least 12 in on both sides and the nose",
            "20 ga minimum firewall installed between engine / fuel cell and cockpit",
            "Metal floorboard or undertray installed",
            "Ground clearance is sufficient for a flat tire",
            "Transmission has a declutching device such as a neutral lockout",
          ],
        },
      ],
    },
    {
      id: "super-sprint",
      label: "Super Sprint",
      title: "CHCA 2026 Super Sprint Technical Inspection",
      summary: "Super Sprint checklist based on Rulebook Section 400.",
      extraFields: [],
      sections: [
        {
          title: "Eligibility and Weight",
          items: [
            "Normally aspirated flat-bottom 2-wheel-drive car",
            "Engine displacement does not exceed 220 cubic inches",
            "Engine has 6 cylinders maximum",
            "Vehicle weight meets 8 lb per cubic inch",
          ],
        },
        {
          title: "Aero and Safety Equipment",
          items: [
            "On-board fire extinguisher system is at least 5 lb and within reach",
            "Safety nets or arm restraints installed",
            "Wing area does not exceed 16 sq ft combined front and rear",
            "Wings do not extend past outside of the tires",
            "Wing pitch cannot be changed by the driver while seated",
            "No studded tires",
            "Fuel cell installed",
          ],
        },
        {
          title: "Structure and Chassis Safety",
          items: [
            "Body provides as much coverage as practical",
            "Competition numbers are at least 12 in on both sides and 9 in on the nose",
            "4-post roll cage installed with required front and rear helmet clearances",
            "If helmet breaks the roll cage plane, safety nets are installed",
            "20 ga minimum firewall installed between engine / fuel cell and cockpit",
            "Metal floorboard or underpan installed",
            "Ground clearance is sufficient for a flat tire",
            "Transmission has a declutching device such as a neutral lockout",
            "Braking system operates on all 4 wheels with dual master cylinders",
            "Fuel lines and linkage are sufficiently supported or reinforced",
            "Mounted starter system operates with on-board or auxiliary battery power",
          ],
        },
      ],
    },
    {
      id: "competition-truck",
      label: "Competition Truck",
      title: "CHCA 2026 Competition Truck Technical Inspection",
      summary: "Competition Truck checklist built from the 2026 rulebook truck requirements.",
      extraFields: [
        {
          name: "competitionTruckDriveType",
          label: "Truck Drive Type",
          type: "select",
          options: ["2WD", "4WD"],
          required: true,
        },
      ],
      sections: [
        {
          title: "Eligibility and Construction",
          items: [
            "Vehicle is a truck or utility vehicle and is 2WD or 4WD only",
            "Vehicle resembles a production truck / utility vehicle",
            "Naturally aspirated only: carbureted or fuel injected; no turbocharger or supercharger",
            "One engine only",
            "Minimum vehicle weight is 2000 lb with driver and fluids",
            "Body is clean, neat, race-ready, and free of major body damage / primer-only panels",
            "Hood has positive fasteners",
            "Doors are fastened in an approved manner",
            "Frame construction meets class rule",
            "Data acquisition is legal if used; no traction control",
          ],
        },
        {
          title: "Driveline and Systems",
          items: [
            "360-degree driveshaft bracket / retainer installed forward of centerline",
            "Transmission complies with Competition Truck rule",
            "Drive axle complies with Competition Truck rule",
            "Suspension complies with Competition Truck rule",
            "Brake system complies with class rule and uses no carbon fiber components",
            "Vehicle has 4 wheels; rim width does not exceed 12 in",
            "Tires are approved by the Technical Director",
            "Approved CHCA fuel cell installed with approved vent and skid plate",
            "Fuel is limited to alcohol, propane, natural gas, or gasoline",
            "Battery is secure; insulated / enclosed as required",
            "Self-starter is in operating order and vehicle starts under its own power",
            "Ignition, fuel shutoff, and master switches are labeled and reachable by the driver",
            "Exhaust exits behind the front of the driver seat and is not exposed in the driver compartment",
          ],
        },
        {
          title: "Roll Cage and Driver Safety",
          items: [
            "Roll cage type construction installed",
            "Front hoop, rear hoop, top bars, rear down braces, diagonal brace, and gussets are present",
            "At least 3 side bars on driver side and 2 on passenger side, or 3 on both sides if co-driver is carried",
            "Minimum helmet clearance to cage is 3 in",
            "Headrest support installed and padded",
            "Required cage padding installed",
            "Inspection hole in main hoop provided",
            "Seat and belt installation complies with General Rule 13",
            "Fire-resistant gloves and shoes present",
            "Helmet present",
            "On-board fire extinguisher system is at least 5 lb",
            "10 lb pit fire extinguisher present",
          ],
        },
      ],
    },
    {
      id: "super-stock-truck",
      label: "Super Stock Truck",
      title: "CHCA 2026 Super Stock Truck Technical Inspection",
      summary: "Super Stock Truck checklist based on Rulebook Section 600.",
      extraFields: [
        {
          name: "superStockTruckDriveType",
          label: "Truck Drive Type",
          type: "select",
          options: ["2WD", "4WD"],
          required: true,
        },
      ],
      sections: [
        {
          title: "Eligibility and Body",
          items: [
            "Manufactured truck only; no utility or sport vehicle body",
            "No turbocharged or supercharged engine",
            "Original body dimensions retained except approved tire clearance",
            "Outside edge of tire tread at top is within 2 in of the fender well",
            "Truck retains standard appearance; hood scoop does not exceed 2 in above hood",
            "Hood remains in original position and uses positive fasteners",
            "Ballast is secure inside the body shell and not in the driver compartment",
            "Doors are fastened in an approved manner",
            "20 ga minimum firewall installed between fuel tank and driver compartment",
            "Stock frame retained with original outside dimensions and crossmembers",
            "No aerodynamic wings",
            "Safety net installed and mounted per class rule",
          ],
        },
        {
          title: "Engine and Chassis",
          items: [
            "OEM cast iron block only",
            "Cast iron or aluminum heads only",
            "Cast iron or aluminum intake only",
            "Stock type distributor only; no magneto",
            "No roller cam or mushroom lifters",
            "No dry sump oil system",
            "Engine setback does not exceed 12 in",
            "Vehicle weight meets 7.5 lb / ci for 2WD or 8.5 lb / ci for 4WD",
            "Wheelbase is within 1 in of manufactured dimension",
            "360-degree driveshaft bracket installed forward of centerline",
            "Transmission is OEM",
            "Solid rear axle housing used; no IRS and no quick-change",
            "Stock suspension / chassis retained except approved reinforcing",
            "Suspension mounts remain in stock locations",
            "Stock-type sway bars only",
            "Shocks are in stock location",
            "No racing or lightweight calipers, rotors, or spindles",
            "No carbon fiber brakes",
            "Vehicle has 4 wheels only",
            "DOT-approved tires only, approved by Technical Director, with no recaps",
            "Approved CHCA fuel cell installed, max 22 gal, with vent and skid plate",
            "Single carburetor or TBI-style fuel injection only",
          ],
        },
        {
          title: "Driver Safety and Electrical",
          items: [
            "Self-starter is in operating order and truck starts under its own power",
            "Ignition, fuel shutoff, and master switches are day-glow orange, labeled, and within reach",
            "Exhaust exits beyond the side panel and behind the front of the driver seat",
            "Basic roll cage design meets class rule",
            "At least 3 side bars on driver side and 2 on passenger side",
            "Minimum helmet clearance to cage is 3 in",
            "Headrest support and required cage padding installed",
            "Fuel restricted to gasoline or race gas only",
            "No nitrogen-bearing additives used",
            "No outerwear worn over fire suit while driving",
            "Approved fire-resistant gloves and shoes present",
            "Helmet present for driver and passenger if applicable",
            "On-board fire extinguisher system is at least 5 lb",
            "10 lb pit fire extinguisher present",
            "Competition numbers are readable on both sides and roof, at least 15 in high",
            "Driver name is displayed on the cab in letters at least 2 in high",
          ],
        },
      ],
    },
    {
      id: "championship",
      label: "Championship",
      title: "CHCA 2026 Championship Technical Inspection",
      summary: "Championship class checklist based on Rulebook Section 700.",
      extraFields: [],
      sections: [
        {
          title: "Eligibility and Engine Limits",
          items: [
            "Open wheel, open cockpit, single-seat, front-engine car only",
            "No rear-engine or mid-engine configuration",
            "Minimum wheelbase is 80 in",
            "No 4-wheel drive or 4-wheel steering",
            "Driver sits behind the engine and ahead of the rear axle",
            "Vehicle appearance matches Championship class standards",
            "No computerized fuel injection, ignition advance, traction control, or transmission",
            "No aluminum engine block",
            "No 2-cycle engine",
            "Engine displacement / induction combination complies with Championship limits",
            "Vehicle weight meets 4.5 lb per cubic inch",
          ],
        },
        {
          title: "Aero, Tires, and Body",
          items: [
            "Wing pitch cannot be changed by the driver while seated",
            "Wings do not extend past the outside of the tires",
            "No studded tires",
            "No tire chains",
            "Vehicle uses 4 tires only",
            "Fuel cell installed",
            "Body provides as much coverage as practical",
            "Competition numbers are at least 12 in on both sides and 5 in on the nose",
          ],
        },
        {
          title: "Safety Systems",
          items: [
            "4-post roll cage installed with front hoop at least 6 in ahead of helmet and rear hoop at least 4 in above helmet",
            "Roll bar tubing size / wall thickness meets class rule",
            "Top corners of cage are gusseted",
            "Padded headrest installed",
            "Throttle design prevents stuck-open condition and uses approved return / toe strap setup",
            "Fuel shutoff valve is within reach of the strapped-in driver",
            "Steering has free movement and turning stops",
            "Pitman arms eliminate reverse steering",
            "Racing steering wheel and quick release hub installed",
            "Open driveshaft has approved 360-degree containment",
            "Approved safety hubs installed",
            "20 ga minimum firewall installed between engine / fuel cell and cockpit",
            "Metal floorboard or underpan installed",
            "Ground clearance is sufficient for a flat tire",
            "Transmission includes a declutching device and is not computerized",
            "Braking system operates on all 4 wheels with dual master cylinders",
            "Fuel lines and linkage are sufficiently supported or reinforced",
            "On-board fire extinguisher system is at least 5 lb",
            "Arm restraints installed",
            "Mounted starter system operates with on-board or auxiliary battery power",
          ],
        },
      ],
    },
    {
      id: "quad",
      label: "Quad",
      title: "CHCA 2026 Quad (ATV) Technical Inspection",
      summary: "Quad / ATV checklist based on Rulebook Section 800.",
      extraFields: [
        {
          name: "quadDriveType",
          label: "Quad Drive Type",
          type: "select",
          options: ["2WD", "4X4"],
          required: true,
        },
      ],
      sections: [
        {
          title: "Vehicle Setup",
          items: [
            "Functional tether-type kill device / ignition cutoff attached to rider and quad",
            "No airfoils, wings, or streamlining devices",
            "Nerf bars installed with closed-loop design",
            "Nerf bars do not extend beyond the widest point measured at front and rear tires",
            "Nerf bar webbing / mesh prevents rider foot from dropping below bars",
            "No sharp protruding or open ends on nerf bars",
            "Exhaust system is securely attached",
            "Exhaust remains inboard of the rider's legs when seated",
            "Overall outside tire width does not exceed 52 in for 2WD or 56 in for 4X4",
            "Self-closing throttle installed",
            "Rear fenders installed or approved for trimming",
          ],
        },
        {
          title: "Engine, Brakes, and Fuel",
          items: [
            "Crankcase / cylinders comply with ATV or approved single-cylinder 4-stroke motorcycle engine rule",
            "Engine displacement and cylinder count comply with selected 2WD / 4X4 class limits",
            "Any regrooved or cut tires are prepared in a safe, workmanlike manner",
            "No rubber or metal studs / foreign material added to tire tread",
            "Front and rear brakes are functional",
            "Brake system is at least as capable as originally manufactured",
            "Fuel is pump gasoline or race gasoline only; premix used only as allowed for 2-strokes",
            "No alcohol / methanol fuel used",
            "No nitrogen-bearing additives used",
          ],
        },
        {
          title: "Rider Gear and Identification",
          items: [
            "Rider is wearing approved motocross gear or leathers in good condition",
            "Helmet is worn whenever machine is in motion",
            "Helmet is clearly labeled with rider name",
            "Helmet certification meets approved standard",
            "Required protective gear is present: boots, gloves, eye / face protection, neck protection, and chest protector or approved leather setup",
            "Front and rear number plates are mounted in a vertical, secure position",
            "Number plates are white with black numbers and no prohibited materials / perforations",
            "Numbers are matching, block style, and at least 6 in high",
            "Handlebars are approved material and are not cracked, broken, or repaired",
          ],
        },
      ],
    },
    {
      id: "junior",
      label: "Junior",
      title: "CHCA 2026 Junior Technical Inspection",
      summary: "Junior class checklist based on Rulebook Section 1000.",
      extraFields: [
        {
          name: "juniorDriverAge",
          label: "Driver Age",
          type: "number",
          required: true,
        },
        {
          name: "juniorOrientationComplete",
          label: "Rookie Orientation Complete",
          type: "select",
          options: ["Yes", "No"],
          required: true,
        },
      ],
      sections: [
        {
          title: "Driver Eligibility",
          items: [
            "Driver age is within Junior class eligibility for the season",
            "Notarized signatures of both parents / legal guardians are on file",
            "Rookie orientation / driving class has been completed and approved",
          ],
        },
        {
          title: "Vehicle Eligibility and Weight",
          items: [
            "Normally aspirated 2-wheel-drive car",
            "Engine package is approved if outside listed Junior combinations",
            "1- or 2-cylinder OHC 4-stroke or single-cylinder 2-stroke meets 1.5 lb / cc and 800 lb minimum if used",
            "4-cylinder overhead cam engine does not exceed 650 cc and meets 1000 lb minimum if used",
            "Pushrod engine does not exceed class displacement rule and meets 1100 lb minimum if used",
            "Race weight includes driver and remaining fuel at end of run",
          ],
        },
        {
          title: "Construction and Safety",
          items: [
            "Construction complies with Open Competition rules and General Rule 13.10",
            "Window nets or arm restraints installed",
            "If no overhead wing is used, over-pan of minimum 0.090 metal is installed",
            "If wing is used, total wing area is at least 3 sq ft",
            "Wing mounts are approved by the Junior Committee",
            "Wing setup complies with Super Sprint Rule 404",
          ],
        },
      ],
    },
    {
      id: "motorcycle",
      label: "Motorcycle",
      title: "CHCA 2026 Motorcycle Technical Inspection",
      summary: "Motorcycle inspection based on Rulebook Section 1200.",
      extraFields: [
        {
          name: "motorcycleDivision",
          label: "Motorcycle Division",
          type: "select",
          options: ["Pro", "Amateur"],
          required: true,
        },
      ],
      sections: [
        {
          title: "Pre-Race Compliance",
          items: [
            "Motorcycle presented clean, race-ready, and with required number plates mounted",
            "Only one vehicle is being presented per paid entry",
            "Rookie orientation completed if rider is a rookie",
            "Machine is available for follow-up tech inspection during the event",
            "Required items are safety-wired / secured as applicable, including kick starter bolts, foot brake, and coolant cap",
          ],
        },
        {
          title: "Rider Safety Gear",
          items: [
            "Rider is wearing approved motocross gear or leathers in good condition",
            "Helmet is worn whenever the motorcycle is in motion",
            "Helmet certification meets approved standard",
            "Required protective apparel is present: boots, gloves, race pants or leathers, eye / face protection, neck protection, and chest protector or approved leather setup",
            "10 lb pit fire extinguisher is present during fueling",
          ],
        },
        {
          title: "Basic Equipment and Powertrain",
          items: [
            "Working kill button installed",
            "Self-closing throttle installed",
            "Front and rear brakes are functional",
            "Ball-end levers or bark buster style guards installed",
            "Repairs / modifications are workmanlike and reliable",
            "Kickstand is secured while on the racetrack",
            "Footrests are folding, blunt, or rubber / plastic covered",
            "Lighting equipment removed or taped over as allowed",
            "Only normally aspirated OEM fuel injected engines are used; no supercharger, turbocharger, or nitrous oxide",
            "OEM motorcycle engine and crankcase are used",
            "No titanium frame",
            "Coolant catch bottle installed on liquid-cooled engines",
            "Fuel meets motorcycle rule",
            "Number plates are mounted front and both sides, legible, and front number is at least 6 in high",
          ],
        },
      ],
    },
    {
      id: "utv-sxs",
      label: "UTV / SXS",
      title: "CHCA 2026 UTV / SXS Technical Inspection",
      summary: "UTV / SXS checklist based on Rulebook Section 1400.",
      extraFields: [],
      sections: [
        {
          title: "Eligibility and Structure",
          items: [
            "Vehicle is a mass-produced UTV / SXS with OEM ROPS / cage origin",
            "Maximum tire size is 30 in",
            "No studded tires",
            "Doors use sheet metal skins or inside bars with sheet metal skins",
            "Competition numbers are at least 12 in high on both sides",
            "Aftermarket welded roll cage installed",
            "Padded headrest installed",
            "Minimum clearance between roll bars and top of helmet is 4 in",
          ],
        },
        {
          title: "Fuel, Engine, and Driveline",
          items: [
            "Stock fuel tank remains in stock location, or approved aftermarket fuel cell is properly mounted and protected",
            "No NOS or nitromethane used",
            "Correct fuel type sticker displayed on both sides",
            "Fuel pump turns off with ignition / master switch and switch is within reach",
            "Fuel lines and fittings are sufficiently supported or reinforced",
            "Stock engine retained",
            "Factory suspension and shock pickup points retained",
            "Stock transmission retained",
            "Open driveshafts or drive chains are guarded",
            "Mounted starter system operates with on-board or auxiliary battery power",
          ],
        },
        {
          title: "Controls and Fire Safety",
          items: [
            "Throttle return springs installed on cable / linkage systems, or drive-by-wire system verified",
            "Toe hook installed on throttle pedal where required",
            "On-board fire extinguisher system is at least 5 lb",
            "Steering wheel is stock or approved quick-release setup",
            "20 ga minimum firewall installed between engine / fuel system and cockpit",
            "Braking system operates efficiently on all 4 wheels",
            "Seat installation complies with General Rule 13.11",
          ],
        },
      ],
    },
    {
      id: "unlimited",
      label: "Unlimited",
      title: "CHCA 2026 Unlimited Technical Inspection",
      summary: "Unlimited class checklist based on Rulebook Section 1500.",
      extraFields: [],
      sections: [
        {
          title: "General Class Requirements",
          items: [
            "Vehicle follows the general car construction rules",
            "Vehicle has been inspected by the Technical Director",
            "No studded tires",
            "Body provides as much coverage as practical",
            "Competition numbers are at least 12 in high on both sides and the nose",
            "Roll cage installed unless vehicle is in another CHCA-approved exempt class",
          ],
        },
        {
          title: "Fuel and Controls",
          items: [
            "Fuel cell installed unless vehicle is in another CHCA-approved class that does not require one",
            "Mechanical fuel injection shutoff valve is within reach if applicable",
            "Fuel lines and linkage are sufficiently supported or reinforced",
            "Steering permits free movement of front wheels and has turning stops",
            "Pitman arms eliminate reverse steering",
            "Approved racing steering wheel installed",
          ],
        },
        {
          title: "Safety Systems",
          items: [
            "20 ga minimum firewall installed between engine / fuel system and cockpit",
            "Braking system operates on all 4 wheels with dual master cylinders",
            "On-board fire extinguisher system is at least 5 lb",
            "Mounted starter system operates with on-board or auxiliary battery power",
          ],
        },
      ],
    },
    {
      id: "rally",
      label: "Rally",
      title: "2026 CHCA Rally Class Technical Inspection Checklist",
      summary: "Rally class inspection with AWD/2WD detail, occupant safety requirements, and vehicle prep checks.",
      extraFields: [
        {
          name: "coDriverName",
          label: "Co-Driver Name",
          type: "text",
          placeholder: "Required if applicable",
        },
        {
          name: "rallyDriveType",
          label: "Rally Class",
          type: "select",
          options: ["AWD", "2WD"],
          required: true,
        },
      ],
      sections: [
        {
          title: "Occupant Safety and Structure",
          items: [
            "Cage built to FIA Appendix J Article 253 or FIA homologation documentation provided (See CHCA Rulebook Sections 901 A and B)",
            "Protective padding installed near occupant helmet areas - material compliant with FIA Standard 8857 2001, type A or SFI 45.1 Specification.",
            "Harnesses compliant and installed for driver and co-driver (if applicable) - FIA Standard 8853/98 or 8853/2016, SFI 16.1, 16.5, or 16.6; not expired or damaged; properly mounted; see Section 901 C",
            "Seat belt cutter(s) present and within reach of all occupants",
            "Seats FIA homologated or designed for motor racing - must be fixed back, not OEM; fixed to vehicle structure; no sliders",
            "Fire suppression system installed and marked (approved options in Section 901 E) - securely mounted with metal hardware; at least one extinguisher reachable when seated; pressure gauge visible; annual inspection certification if dry powder",
          ],
        },
        {
          title: "Fuel, Braking, and Core Vehicle Safety",
          items: [
            "Fuel tank/cell securely mounted - OEM tank or approved fuel cell; shielded from abrasion and impact",
            "Fuel lines protected if underneath vehicle and/or appropriate material if in cabin",
            "Fuel type compliant - gasoline, diesel, or ethanol",
            "Adequate braking system installed",
            "Battery securely mounted with insulated hot terminal - in enclosure if relocated from OEM location and lead-acid",
            "All loose items secured",
            "Chassis modifications maintain structural integrity - see Section 902 A through P",
            "Front & rear tow points installed and marked",
            "Exhaust does not enter passenger compartment, terminates past bodywork",
          ],
        },
        {
          title: "Glass, Doors, and Cabin Protection",
          items: [
            "Windshield is laminated safety glass",
            "Other windows either covered with film or replaced with polycarbonate >=3mm",
            "All other non-laminated glass taped or filmed",
            "Metal sunroof fixed closed or replaced correctly - glass sunroofs must be removed and replaced with metal",
            "Interior door edge protection installed if near occupant",
            "Airbags disabled or removed",
            "Power door locks disabled",
            "Steering lock disabled",
          ],
        },
        {
          title: "Driver and Co-Driver Equipment",
          items: [
            "Driver suit compliant - FIA Standard 8856-2000 or 8856-2018; SFI 3.2A/5 or 3.4/5 Specification; SFI 3.2A/1 Specification with approved fire-resistant underwear (FIA Standard 8856-2000 or SFI 3.3 Specification); driver must have approved gloves",
            "Co-driver suit compliant (if applicable) - FIA Standard 8856-2000 or 8856-2018; SFI 3.2A/5 or 3.4/5 Specification; SFI 3.2A/1 Specification with approved fire-resistant underwear (FIA Standard 8856-2000 or SFI 3.3 Specification)",
            "Helmets certified and not expired - British Standards BS6658-85 type A/FR including all amendments; FIA Standards 8860-2010, 8860-2018, 8859-2015, or 8859-2024; Snell Foundation certification SA2015, EA2016, SA2020, or SA2025; no longer legal ten years after date of manufacture, and if no date sticker exists the helmet is considered expired",
            "Frontal head restraint compliant - HANS systems complying with FIA 8858-2002 or 8858-2010; HYBRID systems complying with FIA 8858-2010; other systems certified to SFI 38.1 less than 5 years old per manufacturer date label",
            "Arm restraints present or window nets installed unless vehicle is equipped with shatterproof windows",
          ],
        },
      ],
    },
  ],
};

